"use strict";
exports.__esModule = true;
var typescript_1 = require("./typescript");
var Shimano = new typescript_1.Bike(2500, "50", 150);
var Tottem = new typescript_1.Bike(2000, "55", 263);
var Bianchi = new typescript_1.Bike(1000, "15", 184);
Shimano.ride();
Shimano.ride();
Shimano.ride();
Shimano.reverse();
Shimano.displayInfo();
Tottem.ride();
Tottem.ride();
Tottem.reverse();
Tottem.reverse();
Tottem.displayInfo();
Bianchi.reverse();
Bianchi.reverse();
Bianchi.reverse();
Bianchi.displayInfo();
